---
# Install CoreOS
- name: Boot into rescue system
  hcloud_server:
    name: "{{ hcloud.name }}"
    rescue: linux64
    state: running
    ssh_keys: "{{ ssh_keys }}"
  connection: local

- name: Wait for SSH to come up
  wait_for:
    host: "{{ hcloud.public_ipv4 }}"
    port: 22
    delay: 10
    timeout: 120
  connection: local

- name: Template ignition.json
  template:
    src: "{{ ignition_template }}"
    dest: /root/ignition.json

- name: Install CoreOS
  shell: |
    wget https://raw.github.com/coreos/init/master/bin/coreos-install
    chmod +x coreos-install
    ./coreos-install -d /dev/sda -i /root/ignition.json
    reboot
